# Generated by Django 3.2.6 on 2022-03-20 10:24

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('blog_img', models.ImageField(upload_to='blog')),
                ('blog_name', models.CharField(max_length=150)),
                ('blog_category', models.CharField(max_length=100)),
                ('blog_description', ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
