# Generated by Django 3.2.6 on 2022-03-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('title', models.CharField(max_length=30)),
                ('favicon', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
