# Generated by Django 3.2.6 on 2022-03-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin_profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='admin_profile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
