# Generated by Django 3.2.6 on 2022-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_admin_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
