# Generated by Django 3.2.6 on 2022-03-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_id', models.CharField(blank=True, max_length=50)),
                ('coupan_name', models.CharField(max_length=50)),
                ('Coupon_expire_date', models.DateField()),
                ('quantity', models.IntegerField(default=100)),
                ('used', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('Coupon_created', models.DateField(auto_now=True)),
                ('message', models.CharField(default='Applied', help_text='User will see this messge when he/she apply the coupen', max_length=100)),
                ('discount', models.CharField(help_text='You Can Ammount or Percent of Ammount Eg: 100 or 10%', max_length=10)),
                ('minimum_order_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meassuement', models.CharField(choices=[('cm', 'cm'), ('MM', 'MM'), ('Inch', 'Inch')], max_length=10, verbose_name='size')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='productUses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('uses', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='product')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('base', models.IntegerField()),
                ('transports', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('about', models.TextField()),
                ('long_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory')),
                ('color', models.ManyToManyField(to='shop.productStyle')),
                ('material', models.ManyToManyField(to='shop.productMaterial')),
                ('size', models.ManyToManyField(to='shop.productSize')),
                ('thickness', models.ManyToManyField(to='shop.productThickness')),
                ('uses', models.ManyToManyField(to='shop.productUses')),
            ],
        ),
    ]
