# Generated by Django 3.2.6 on 2022-03-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupons_coupan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productthickness',
            name='thickid',
            field=models.IntegerField(default=0),
        ),
    ]
