# Generated by Django 3.2.6 on 2022-03-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productthickness_thickid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthickness',
            name='thickid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
