# Generated by Django 3.2.6 on 2022-03-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productthickness_thickid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='mateid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
