# Generated by Django 3.2.6 on 2022-03-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productmaterial_mateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='mateid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
