# Generated by Django 3.2.6 on 2022-03-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productmaterial_mateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='mateid',
        ),
        migrations.RemoveField(
            model_name='productthickness',
            name='thickid',
        ),
        migrations.AddField(
            model_name='productthickness',
            name='thick_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
