# Generated by Django 3.2.6 on 2022-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220329_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='mate_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productstyle',
            name='col_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productuses',
            name='use_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
