# Generated by Django 3.2.6 on 2022-03-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220329_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='price',
            new_name='prices',
        ),
    ]
