# Generated by Django 3.2.6 on 2022-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_price_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prices',
            name='transports',
            field=models.IntegerField(default=0),
        ),
    ]
