# Generated by Django 3.2.6 on 2022-03-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220329_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='material',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='uses',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='material',
            field=models.ManyToManyField(to='shop.productMaterial'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='uses',
            field=models.ManyToManyField(to='shop.productUses'),
        ),
    ]
