# Generated by Django 3.2.6 on 2022-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220329_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
