# Generated by Django 3.2.6 on 2022-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_msg',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
