# Generated by Django 3.2.6 on 2022-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contact_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_msg',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
